### ISSUE TITLE
User can view general statistics on launches

### ISSUE THREAD

**Issue by kelly-hansen** [kelly-hansen/launchlist#21]
## 💰 Feature

User can view general statistics on launches

## 🗒️ Notes

Use preexisting data in launch data object retrieved from API

## ✅ Tasks

- [x] In main.js, beneath render of 'Upcoming Rocket Launches' heading, render p elements for statistics: Next 10 Days and Total
- [x] Use 'count' property of launchList object for value of Total stat
- [x] For Next 10 Days:
   - [x] Declare a new variable count10Days, initialized to 0
   - [x] Declare a new variable date10Days, initialized to new Date() object 10 days in the future
   - [x] loop through array of upcoming launches, and for each launch, create a new Date() object using the launch's window_start property
   - [x] If the new date comes before date10Days, count10Days++
- [x] Use count10Days for value of Next 10 Days stat
- [x] Replicate stats for Recent Rocket Launches (with launches in PREVIOUS 10 days)
